apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-storage-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # Or a more scoped ClusterRole if needed
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: agrocd
